// Renders every Maths draft into content/maths/REVIEW.md for human review.
//   node tools/content/render_review.mjs
// Everything shown is produced by the engine itself, so the reviewer sees exactly what pupils will see.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import * as lib from "../../src/engine/lib/maths.js";
import { instantiate, renderWorked } from "../../src/engine/template.js";
import { renderCard, cardCheckTemplate, practicePlan } from "../../src/engine/teach.js";

const DIR = new URL("../../content/maths/", import.meta.url);
const lessons = readdirSync(DIR).filter((f) => /^\d+\.json$/.test(f))
  .map((f) => JSON.parse(readFileSync(new URL(f, DIR), "utf8"))).sort((a, b) => a.lesson_no - b.lesson_no);
const spine = JSON.parse(readFileSync(new URL("../../data/spine/mathematics.json", import.meta.url), "utf8"));
const meta = Object.fromEntries(spine.terms.flatMap((t) => t.lessons).map((l) => [l.lesson_no, l]));
const SAMPLE_LESSON = 3, SAMPLE_SEED = 2026;

/** Same rule as the tests: a word is a token with a letter or digit; symbols such as = × • are not counted. */
const words = (t) => t.split(/\s+/).filter((w) => /[\p{L}\p{N}]/u.test(w)).length;
const nb = (s) => String(s).replace(/ /g, " ");
const quote = (t) => nb(t).split("\n").map((l) => `> ${l}`).join("\n");

function renderQuestion(q) {
  const out = [`**${q.prompt.replace(/\n/g, " ")}**${q.unit ? ` _(answer in ${q.unit})_` : ""}`];
  if (q.options) q.options.forEach((o, i) => out.push(`${i === q.correctIndex ? "- ✅" : "- ◻️"} ${o.text}${(o.misconception || o.explain) && !(q.type === "spot_error" && i !== q.correctIndex) ? `  \n  _↳ ${i === q.correctIndex && q.type === "spot_error" ? "explanation shown after answering" : "feedback if chosen"}: ${o.explain || o.misconception}_` : ""}`));
  if (q.items) out.push(`Shown as: ${q.items.join(" · ")}  \nCorrect order: ${q.answer}`);
  if (q.type === "numeric") {
    out.push(`Answer: **${q.answer}${q.unit ? " " + q.unit : ""}**`);
    for (const m of q.misconceptions) out.push(`- Wrong answer **${m.value}** (${m.id}) → “${m.explain}”`);
  }
  if (q.hint) out.push("", `Hint (draft): ${q.hint}`);
  if (q.solution) out.push("", "Full working after a second miss:", "", ...q.solution.map((x) => `> ${x}  `));
  return nb(out.join("\n"));
}

const cardBlock = (l, c, seed) => {
  const r = renderCard(c, lib);
  const tpl = cardCheckTemplate(l, c);
  const q = instantiate(tpl, seed, lib, l.lesson_no);
  return [`**Card ${c.id}** (draft)`, "", `> ${nb(r.idea)}`, ">", ...r.example.map((x) => `> _${nb(x)}_  `), "",
    `Check question (\`${tpl.id}\`, level ${tpl.level}${tpl.review === "authored" ? ", **authored**" : ""}${c.check.ref ? ", reused from practice" : ""}):`, "",
    renderQuestion(q), ""];
};

const lines = [
  "# Maths Form 1: drafts for review (Lesson 0 + Lessons 1–16)", "",
  "Generated by `npm run review` from `content/maths/*.json`. Every number below was computed by the engine.",
  "Notes, teach cards and worked examples are **status: draft**. Templates marked **authored** have answers fixed by the author",
  "(definitions and facts), so their correctness rests on review rather than on computation.", "",
  "Teach mode for every lesson: cards (idea + example + 1 level-1 check) → worked example → practice (levels 1–3) → the note as a summary.",
  "A wrong or \"I don't know\" check answer re-shows that card's example, then asks a fresh variant once before moving on.", "",
  `## Sample rendered lesson: Lesson ${SAMPLE_LESSON} in teach mode`, "",
];

const sample = lessons.find((l) => l.lesson_no === SAMPLE_LESSON);
lines.push(`### Lesson ${SAMPLE_LESSON}: ${meta[SAMPLE_LESSON].title}`, "");
sample.teach.cards.forEach((c, i) => lines.push(...cardBlock(sample, c, SAMPLE_SEED + i)));
const swe = renderWorked(sample.worked_example, lib);
lines.push("**Worked example**", "", nb(swe.problem), "", ...swe.steps.map((s, i) => nb(`${i + 1}. ${s}`)), "", nb(`**Answer:** ${swe.answer}`), "",
  "**Practice** (one generated question per template, easiest first)", "");
practicePlan(sample).forEach((id, i) => {
  const q = instantiate(sample.questions.find((t) => t.id === id), SAMPLE_SEED + 50 + i, lib, SAMPLE_LESSON);
  lines.push(`**P${i + 1}** (${q.type}, level ${q.level})`, "", renderQuestion(q), "");
});
lines.push("**Summary (the note)**", "", quote(sample.note.text), "");

lines.push("---", "", "## All drafts", "", "| Lesson | Title | Prerequisites | Cards | Note words* | Templates (L1/L2/L3) |", "|---|---|---|---|---|---|");
for (const l of lessons) {
  const lv = [1, 2, 3].map((n) => (l.questions || []).filter((q) => q.level === n).length).join("/");
  lines.push(`| ${l.lesson_no} | ${meta[l.lesson_no].title} | ${l.prerequisites.join(", ") || "none"} | ${l.teach ? l.teach.cards.length : "–"} | ${words(l.note.text)} | ${l.kind === "readiness" ? `readiness check (${l.readiness.items.length} items)` : lv} |`);
}
lines.push("", "\* Words = tokens containing a letter or digit; symbols such as =, ×, • are not counted. Limit: 150.", "");

for (const l of lessons) {
  lines.push(`## Lesson ${l.lesson_no}: ${meta[l.lesson_no].title}`, "", `Chapter: ${meta[l.lesson_no].chapter}. Prerequisites: ${l.prerequisites.join(", ") || "none"}.`, "",
    "**Note** (draft)", "", quote(l.note.text), "");
  if (l.kind === "readiness") {
    lines.push("**Primary 6 readiness check** (sets a readiness score and weak areas; never Form 1 mastery or coverage)", "",
      "| # | Area | Template | Sample question |", "|---|---|---|---|");
    l.readiness.items.forEach((it, i) => {
      const t = l.questions.find((x) => x.id === it.template);
      lines.push(`| ${i + 1} | ${l.readiness.areas[t.area]} | \`${t.id}\` | ${nb(instantiate(t, 1, lib, 0).prompt)} |`);
    });
    lines.push("", `An area is weak when fewer than two thirds of its questions are right. "I don't know" counts as wrong.`, "");
    continue;
  }
  lines.push("**Teach cards**", "");
  l.teach.cards.forEach((c, i) => lines.push(...cardBlock(l, c, 1 + i)));
  const we = renderWorked(l.worked_example, lib);
  lines.push("**Worked example** (draft)", "", nb(we.problem), "", ...we.steps.map((s, i) => nb(`${i + 1}. ${s}`)), "", nb(`**Answer:** ${we.answer}`), "",
    "**Practice templates** (one sample each, seed 1)", "");
  for (const t of l.questions) {
    const q = instantiate(t, 1, lib, l.lesson_no);
    lines.push(`<details><summary><code>${t.id}</code>: ${t.type}, level ${t.level}${t.review === "authored" ? ", <b>authored</b>" : ""}</summary>`, "", renderQuestion(q), "", "</details>", "");
  }
}
writeFileSync(new URL("REVIEW.md", DIR), lines.join("\n"), "utf8");
console.log(`wrote content/maths/REVIEW.md (${lessons.length} lessons)`);
