"""Builds docs/audit/{subject}.md and docs/audit/README.md: a question-type audit of the 9 non-Maths subjects.

Lesson titles come from data/spine/{subject}.json. The judgement (class, question types, assets, notes) is in
tools/audit/audit_data.py, one line per spine row. Integration, evaluation, remediation and catch-up rows are
"reuse": they draw mixed review from earlier lessons and add no new items.

    python tools/audit/build_audit.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from audit_data import SUBJECTS  # noqa: E402

REUSE_KINDS = {"integration", "evaluation", "remediation", "catch_up"}
CLASSES = {
    "C": ("computed", "yes: code computes the answer"),
    "F": ("fact table", "yes: against an authored table"),
    "A": ("authored", "yes: against an authored key"),
    "X": ("paper-only", "no: self-check against a model answer"),
    "D": ("deferred", "no: needs audio or equipment"),
}
TYPES = {
    "TPL": "templated (computed)", "TBL": "templated from a fact table", "MCQ": "authored MCQ",
    "CLZ": "cloze", "ORD": "ordering", "MAT": "matching", "MAT(sort)": "matching (sort into groups)",
    "LBL": "labelling", "SPOT": "spot the error", "PAP": "paper-only",
}
# Estimated P1 review items per teachable row, by class (see the method in README.md).
P1_WEIGHT = {"C": 2, "F": 4, "A": 7, "X": 3, "D": 0}
KB = {"d": 8, "m": 40, "g": 0}  # drawn SVG, drawn map, drawn by code at run time


def asset_list(s):
    out = []
    for part in [p.strip() for p in re.split(r",(?![^()]*\))", s) if p.strip()]:  # commas outside (...)
        kind, name = part.split(":", 1)
        out.append((kind, re.sub(r"\s*\(.*\)$", "", name).strip(), part))
    return out


def short(t, n=90):
    t = " ".join(t.split())
    return t if len(t) <= n else t[: n - 1].rstrip() + "…"


def analyse(slug, spec):
    spine = json.loads((ROOT / f"data/spine/{slug}.json").read_text(encoding="utf-8"))
    rows = [(t["term"], l) for t in spine["terms"] for l in t["lessons"]]
    by_seq = {r[0]: r for r in spec["rows"]}
    teach, reuse = [], []
    for term, l in rows:
        if l["kind"] in REUSE_KINDS:
            if l["seq"] in by_seq:
                raise SystemExit(f"{slug} row {l['seq']} is {l['kind']} but has an audit entry")
            reuse.append((term, l))
            continue
        if l["seq"] not in by_seq:
            raise SystemExit(f"{slug} row {l['seq']} ({l['title']}) has no audit entry")
        seq, cls, types, assets, note = by_seq[l["seq"]]
        for ty in types.split():
            if ty not in TYPES:
                raise SystemExit(f"{slug} row {seq}: unknown type {ty}")
        teach.append(dict(term=term, l=l, cls=cls, types=types.split(), assets=asset_list(assets), note=note))
    extra = set(by_seq) - {l["seq"] for _, l in rows}
    if extra:
        raise SystemExit(f"{slug}: audit entries for rows not in the spine: {sorted(extra)}")
    count = {c: sum(1 for x in teach if x["cls"] == c) for c in CLASSES}
    unique = {}
    for x in teach:
        for kind, name, _ in x["assets"]:
            unique.setdefault((kind, name), []).append(x["l"]["seq"])
    p1_rows = sum(P1_WEIGHT[x["cls"]] for x in teach)
    p1_drawn = sum(1 for (k, _) in unique if k in "dm")
    p1 = p1_rows + p1_drawn + len(spec["conventions"])
    n = len(teach)
    return dict(slug=slug, spec=spec, spine=spine, teach=teach, reuse=reuse, count=count, unique=unique, n=n,
                p1=p1, p1_rows=p1_rows, p1_drawn=p1_drawn,
                pct_c=100 * count["C"] / n, pct_cf=100 * (count["C"] + count["F"]) / n,
                kb=sum(KB[k] for (k, _) in unique),
                drawn=sum(1 for (k, _) in unique if k == "d"), maps=sum(1 for (k, _) in unique if k == "m"),
                gen=sum(1 for (k, _) in unique if k == "g"))


def lesson_label(l):
    if l.get("lesson_no") is not None:
        return str(l["lesson_no"])
    m = re.match(r"\s*(PW\s*\d+|Practical Work\s*\d+|GW\s*\d+|FS\s*\d+|Further stud(?:y|ies)\s*\d+|Guided work\s*\d+)",
                 l["title"], re.I)
    return re.sub(r"\s+", " ", m.group(1)) if m else "—"


def subject_md(a):
    s, sp = a["spec"], a["spine"]
    L = [f"# {sp['subject_label']} (Form 1): question-type audit", ""]
    L += [f"Audit only, no content written. Source: `data/spine/{a['slug']}.json` "
          f"({sum(1 for t in sp['terms'] for _ in t['lessons'])} rows: {a['n']} teachable, {len(a['reuse'])} reuse). "
          "Generated by `python tools/audit/build_audit.py`; the judgements are in `tools/audit/audit_data.py`.", ""]
    L += ["**Classes** (one per row, by the main kind of practice the row allows):", ""]
    for c, (name, ver) in CLASSES.items():
        L.append(f"- **{c}** {name}: code verifies? {ver}")
    L += ["", "Question types: " + "; ".join(f"`{k}` {v}" for k, v in TYPES.items()) + ".", ""]
    L += ["Assets: `d:` drawn SVG diagram, `m:` drawn SVG map, `g:` drawn by code from the question data "
          "(no file; answers stay computed).", ""]
    c = a["count"]
    L += ["## At a glance", "",
          "| Teachable rows | C computed | F fact table | A authored | X paper-only | D deferred | Code-generated (C+F) | Est. P1 items |",
          "|---|---|---|---|---|---|---|---|",
          f"| {a['n']} | {c['C']} | {c['F']} | {c['A']} | {c['X']} | {c['D']} | {a['pct_cf']:.0f}% | ~{a['p1']} |", ""]
    L += [s["summary"], ""]
    L += ["## Per lesson", "",
          "| Row | Lesson | Title (from the spine) | Class | Question types | Code verifies? | Assets | Notes |",
          "|---|---|---|---|---|---|---|---|"]
    for x in a["teach"]:
        l = x["l"]
        ver = {"C": "yes (computed)", "F": "yes (table)", "A": "yes (key)", "X": "no", "D": "no"}[x["cls"]]
        assets = ", ".join(p for _, _, p in x["assets"]) or "—"
        L.append(f"| {l['seq']} | {lesson_label(l)} | {short(l['title']).replace('|', '/')} | {x['cls']} | "
                 f"{', '.join(x['types'])} | {ver} | {assets} | {x['note'] or ''} |")
    if a["reuse"]:
        rows = ", ".join(str(l["seq"]) for _, l in a["reuse"])
        kinds = sorted({l["kind"].replace("_", "-") for _, l in a["reuse"]})
        L += ["", f"Reuse rows ({', '.join(kinds)}): {rows}. No new items: mixed review drawn from the lessons they "
              "assess. Integration activities that ask for a written answer get a paper-only task with a model answer."]
    L += ["", "## Assets needed", ""]
    if a["unique"]:
        L += ["| Asset | Kind | Rows | Est. size |", "|---|---|---|---|"]
        for (kind, name), seqs in sorted(a["unique"].items(), key=lambda kv: ("dmg".index(kv[0][0]), kv[0][1])):
            label = {"d": "drawn SVG", "m": "drawn SVG map", "g": "drawn by code"}[kind]
            size = f"~{KB[kind]} KB" if KB[kind] else "code only"
            L.append(f"| {name} | {label} | {', '.join(map(str, seqs))} | {size} |")
        L += ["", f"Estimated total for drawn files: ~{a['kb']} KB (drawn SVG ~8 KB each, maps ~40 KB each, "
              "simplified and minified)."]
    else:
        L.append("None.")
    L += ["", "### Offline and audio", "", s["offline"], ""]
    L += ["## Engine gaps", "", s["gaps"], ""]
    L += ["## Review burden (P1)", "",
          f"Estimate: **~{a['p1']} P1 items** = {a['p1_rows']} from the rows "
          f"({c['C']} C × {P1_WEIGHT['C']} + {c['F']} F × {P1_WEIGHT['F']} + {c['A']} A × {P1_WEIGHT['A']} + "
          f"{c['X']} X × {P1_WEIGHT['X']}; deferred rows count 0 for now) + {a['p1_drawn']} drawn diagrams or maps "
          f"(labels must be right) + {len(s['conventions'])} conventions to settle first:", ""]
    for conv in s["conventions"]:
        L.append(f"- {conv}")
    L += ["", "Reviewer: " + s["reviewer"], ""]
    L += ["## Risks and notes", "", s["risks"], ""]
    return "\n".join(L)


def readme_md(all_a):
    L = ["# Subject audit: the 9 non-Maths subjects", "",
         "Audit only: no lesson content was written. One file per subject, plus this summary. "
         "Regenerate with `python tools/audit/build_audit.py` (judgements in `tools/audit/audit_data.py`).", "",
         "## Method", "",
         "Every spine row is either **teachable** (lesson, practical, group work, further study, guided work) or "
         "**reuse** (integration, evaluation, remediation, catch-up: mixed review, no new items). Each teachable row "
         "gets one class, by the main kind of practice it allows:", ""]
    for c, (name, ver) in CLASSES.items():
        L.append(f"- **{c}** {name}: code verifies? {ver}")
    L += ["",
          "**% templatable** below has two figures: *computed* (C, answers worked out by code, as in Maths) and "
          "*code-generated* (C + F: code also builds questions from an authored fact table, so one reviewed table "
          "gives many variants).", "",
          "**P1 estimate** per teachable row: C = 2, F = 4, A = 7, X = 3, D = 0 (later), plus 1 per drawn "
          "diagram or map, plus the subject's open conventions. Calibration: Maths Lessons 0–16 were mostly C and "
          "produced 24 P1 items, about 1.5 per lesson, so C = 2 errs on the high side. These are estimates for "
          "planning, not counts.", "",
          "## Summary", "",
          "| Subject | Teachable rows | Computed (C) | Code-generated (C+F) | Authored (A) | Paper-only (X) | "
          "Deferred (D) | Est. P1 | P1 per row | Drawn SVG | Maps | Code-drawn | Drawn files (est.) |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for a in sorted(all_a, key=lambda a: -a["pct_cf"]):
        c = a["count"]
        L.append(f"| [{a['spine']['subject_label']}]({a['slug']}.md) | {a['n']} | {c['C']} ({a['pct_c']:.0f}%) | "
                 f"{c['C'] + c['F']} ({a['pct_cf']:.0f}%) | {c['A']} | {c['X']} | {c['D']} | ~{a['p1']} | "
                 f"{a['p1'] / a['n']:.1f} | {a['drawn']} | {a['maps']} | {a['gen']} | ~{a['kb']} KB |")
    tot = lambda k: sum(a[k] for a in all_a)  # noqa: E731
    L += [f"| **Total** | {tot('n')} | {sum(a['count']['C'] for a in all_a)} | "
          f"{sum(a['count']['C'] + a['count']['F'] for a in all_a)} | {sum(a['count']['A'] for a in all_a)} | "
          f"{sum(a['count']['X'] for a in all_a)} | {sum(a['count']['D'] for a in all_a)} | ~{tot('p1')} | | "
          f"{tot('drawn')} | {tot('maps')} | {tot('gen')} | ~{tot('kb')} KB |", ""]
    L += ["Sorted by code-generated %. Shared diagrams are counted once per subject, so the size total "
          "overstates a little (see Shared assets).", "", "## Rankings", ""]
    def rank(title, key, rev, fmt):
        out = [f"**{title}**", ""]
        for i, a in enumerate(sorted(all_a, key=key, reverse=rev), 1):
            out.append(f"{i}. {a['spine']['subject_label']}: {fmt(a)}")
        return out + [""]
    L += rank("By % templatable (code-generated, then computed)", lambda a: (a["pct_cf"], a["pct_c"]), True,
              lambda a: f"{a['pct_cf']:.0f}% code-generated, {a['pct_c']:.0f}% computed")
    L += rank("By P1 load per teachable row (lightest first)", lambda a: a["p1"] / a["n"], False,
              lambda a: f"{a['p1'] / a['n']:.1f} per row, ~{a['p1']} in total")
    L += rank("By asset needs (lightest first: drawn files, then audio-deferred rows)",
              lambda a: (a["kb"], a["count"]["D"]), False,
              lambda a: f"~{a['kb']} KB drawn (diagrams: {a['drawn']}, maps: {a['maps']}), deferred rows: {a['count']['D']}")
    L += [SUMMARY_TAIL]
    return "\n".join(L)


from audit_data import SUMMARY_TAIL  # noqa: E402


def main():
    out = ROOT / "docs/audit"
    out.mkdir(parents=True, exist_ok=True)
    all_a = [analyse(slug, spec) for slug, spec in SUBJECTS.items()]
    for a in all_a:
        (out / f"{a['slug']}.md").write_text(subject_md(a), encoding="utf-8", newline="\n")
    (out / "README.md").write_text(readme_md(all_a), encoding="utf-8", newline="\n")
    for a in sorted(all_a, key=lambda a: -a["pct_cf"]):
        c = a["count"]
        print(f"{a['slug']:18} rows {a['n']:3}  C {c['C']:2} F {c['F']:2} A {c['A']:2} X {c['X']:2} D {c['D']:2}  "
              f"C+F {a['pct_cf']:3.0f}%  P1 ~{a['p1']:3}  {a['kb']} KB")


if __name__ == "__main__":
    main()
