"""Phase 1 pipeline: PDFs -> raw spines -> overrides -> final spines + issues.md.

    python tools/spine/build.py

Outputs
  data/spine/raw/{subject}.json   parser output, never edited by hand
  data/spine/{subject}.json       raw + approved overrides + labelled calendar breaks (what the app reads)
  data/spine/issues.md            validation report for all subjects
Inputs
  data/sheets/*.pdf
  data/spine/overrides/{sheet}.json     human-approved fixes, each with reason + approved_by
                                        ({sheet} = subject as printed on the sheet, e.g. geography-ok)
  data/calendar/{year}.json             official school calendar; spines are checked against it (info)
"""
import json
import re
import sys
from collections import Counter
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import overrides as ovr  # noqa: E402
import parse_sheets  # noqa: E402
import validate_spine as val  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
SHEETS = ROOT / "data" / "sheets"
SPINE = ROOT / "data" / "spine"
CALENDAR = ROOT / "data" / "calendar"


def slug(subject):
    return re.sub(r"[^a-z0-9]+", "-", subject.lower()).strip("-")


def weekdays_between(a, b):
    """School days (Mon-Fri) strictly between dates a and b."""
    n, x = 0, a + timedelta(days=1)
    while x < b:
        n += x.weekday() < 5
        x += timedelta(days=1)
    return n


def label_breaks(spine):
    """Gaps in the union of lesson windows. >=2 school weeks = holiday, 1 week = evaluation."""
    windows = sorted((date.fromisoformat(l["start"]), date.fromisoformat(l["end"]))
                     for l in val.lessons_of(spine) if l["start"] and l["end"] and l["start"] <= l["end"])
    breaks, cover_end = [], None
    for s, e in windows:
        if cover_end and s > cover_end:
            weeks = (weekdays_between(cover_end, s) + 1) // 5  # 4 missing days (a Monday holiday) still count as a week
            if weeks >= 1:
                breaks.append({"type": "holiday" if weeks >= 2 else "evaluation",
                               "start": (cover_end + timedelta(days=1)).isoformat(),
                               "end": (s - timedelta(days=1)).isoformat(), "school_weeks": weeks})
        cover_end = e if cover_end is None else max(cover_end, e)
    return breaks


def assign_assesses(spine):
    """Assessment rows (integration/evaluation/remediation) get `assesses`: the chapter they name,
    or their own chapter when they name none. Unmatched labels get None (the validator warns)."""
    chapters = list(dict.fromkeys(l["chapter"] for l in val.lessons_of(spine)))
    for l in val.lessons_of(spine):
        if l["kind"] in val.ASSESSMENT_KINDS and "assesses" not in l:
            label = val.assessment_label(l["title"])
            l["assesses"] = val.match_chapter(label, chapters) if label else l["chapter"]


def term_starts(spine):
    return {t["term"]: t["lessons"][0]["start"] for t in spine["terms"] if t["lessons"] and t["term"]}


def cross_subject(spines):
    """Term boundaries that differ from the majority of sheets, and the shared break calendar (info)."""
    notes = []
    starts = {s["subject"]: term_starts(s) for s in spines}
    for term in (2, 3):
        vals = [v[term] for v in starts.values() if term in v]
        if not vals:
            continue
        mode, _ = Counter(vals).most_common(1)[0]
        odd = {subj: v[term] for subj, v in starts.items() if term in v and v[term] != mode}
        missing = [subj for subj, v in starts.items() if term not in v]
        notes.append(f"- Term {term}: most sheets start on {mode}. Different: "
                     + (", ".join(f"{k} {v}" for k, v in sorted(odd.items())) or "none")
                     + (f". No Term {term} header: {', '.join(missing)}" if missing else "") + ".")
    notes += ["", "- Breaks are per subject: a sheet only shows a holiday where it leaves a gap. Long windows "
              "(e.g. chemistry 2026-12-14 to 2027-02-01, geography 2026-11-30 to 2027-02-06) hide the Christmas holiday, "
              "and sheets disagree on when teaching resumes in January (physics/English 2027-01-04, maths 2027-01-18). "
              "The app should not infer the school calendar from one sheet."]
    return notes


def render(results, notes):
    rank = {"error": 0, "warn": 1, "info": 2}
    out = ["# Spine validation: Form 1, 2026-27", "",
           "Generated by `python tools/spine/build.py`. **Only overrides in `data/spine/overrides/` have been applied.** "
           "Every other issue lists a *proposed* fix for your decision.", "",
           "## Summary", "", "| Subject | Rows | Errors | Warnings | Info | Overrides applied |", "|---|---|---|---|---|---|"]
    for spine, issues in results:
        c = Counter(i["severity"] for i in issues)
        out.append(f"| {spine['subject_label']} | {len(val.lessons_of(spine))} | {c['error']} | {c['warn']} | {c['info']} | "
                   f"{len(spine.get('overrides_applied', []))} |")
    out += ["", "## Across subjects", ""] + notes + [""]
    for spine, issues in results:
        issues = sorted(issues, key=lambda i: (rank[i["severity"]], i["seqs"][0] if i["seqs"] else 0))
        c = Counter(i["severity"] for i in issues)
        out += [f"## {spine['subject_label']} ({spine['source']})", "",
                f"{c['error']} errors, {c['warn']} warnings, {c['info']} info.", ""]
        for ov in spine.get("overrides_applied", []):
            out.append(f"- Applied override `{ov['id']}` ({ov['op']}, approved by {ov['approved_by']}): {ov['reason']}")
        if spine.get("overrides_applied"):
            out.append("")
        for n, it in enumerate(issues, 1):
            where = ", ".join(str(s) if s == r else f"{s} (sheet row {r})" for s, r in zip(it["seqs"], it["rows"])) or "-"
            out += [f"### {n}. [{it['severity'].upper()}] {it['check']} (seq {where})", "",
                    f"- **Problem:** {it['problem']}", f"- **Proposed fix:** {it['fix']}", ""]
        if spine["breaks"]:
            out += ["**Calendar breaks** (labelled in the spine; holidays become catch-up windows):", ""]
            out += [f"- {b['type']}: {b['start']} to {b['end']} ({b['school_weeks']} school week(s))" for b in spine["breaks"]]
            out.append("")
    out += ["## Assumptions (please confirm)", "",
            "- Academic year 2026-27 runs 1 Sep 2026 to 31 Jul 2027; not checked against the official MINESEC calendar.",
            "- Term boundaries are taken from each sheet's term headers.",
            "- Public holidays (11 Feb, 1 May, 20 May, ...) are not checked against lesson windows.",
            "- Breaks are gaps in the union of all lesson windows of one subject, measured in school weeks (Mon-Fri).",
            "- `dropped-ligatures` and `chapter-mismatch` are heuristics: they flag, never decide.", ""]
    return "\n".join(out)


def main():
    pdfs = sorted(SHEETS.glob("*.pdf"))
    if not pdfs:
        sys.exit(f"no PDFs in {SHEETS}")
    (SPINE / "raw").mkdir(parents=True, exist_ok=True)
    results, written, cal = [], set(), None
    for pdf in pdfs:
        raw = parse_sheets.parse_pdf(pdf)
        name = slug(raw["subject"]) or pdf.stem
        (SPINE / "raw" / f"{name}.json").write_text(json.dumps(raw, indent=2, ensure_ascii=False), encoding="utf-8")
        ov_path = SPINE / "overrides" / f"{name}.json"
        ovs = json.loads(ov_path.read_text(encoding="utf-8"))["overrides"] if ov_path.exists() else []
        try:
            spine, resolved = ovr.apply(raw, ovs)
        except ovr.OverrideError as e:
            sys.exit(f"{name}: {e}")
        spine["breaks"] = label_breaks(spine)
        assign_assesses(spine)
        out_name = slug(spine["subject"])  # may differ from `name` after a subject override
        issues = val.validate(spine, val.load_rules(out_name), resolved)
        cal_path = CALENDAR / f"{spine['year']}.json"
        if cal_path.exists():
            cal = json.loads(cal_path.read_text(encoding="utf-8"))
            issues += val.validate_calendar(spine, cal)
        for ov in ovs:
            if ov.get("ambiguous"):
                issues.append({"severity": "warn", "check": "ligature-ambiguous", "seqs": [], "rows": [],
                               "problem": "Several dictionary repairs fit: " + "; ".join(
                                   f"{w} -> {' / '.join(c)}" for w, c in ov["ambiguous"].items()) + ".",
                               "fix": "Pick one per word; it goes into the ligature override."})
        out = SPINE / f"{out_name}.json"
        out.write_text(json.dumps(spine, indent=2, ensure_ascii=False), encoding="utf-8")
        written.add(out)
        results.append((spine, issues))
        c = Counter(i["severity"] for i in issues)
        print(f"{pdf.name:50s} -> {out_name}.json  rows={len(val.lessons_of(spine)):3d}  "
              f"errors={c['error']} warn={c['warn']} info={c['info']} overrides={len(ovs)}")
    for stale in set(SPINE.glob("*.json")) - written:
        stale.unlink()  # e.g. geography-ok.json after the subject rename
        print(f"removed stale {stale.name}")
    spines = [s for s, _ in results]
    notes = cross_subject(spines)
    if cal:
        notes.append(f"- Calendar `data/calendar/{cal['year']}.json` is {cal.get('status', '?')}: "
                     f"{val.calendar_todos(cal)} dates still TODO; drift checks skip them.")
    (SPINE / "issues.md").write_text(render(results, notes), encoding="utf-8")
    print("-> data/spine/issues.md")


if __name__ == "__main__":
    main()
